### ISSUE TITLE
 error C2146

### ISSUE THREAD

**Issue by tonimora74** [skeggse/node-rijndael#12]
Hello all!

when I to try: "npm install node-rijndael" I have this error (It seems a compilation error):

c:\users\equipo\.node-gyp\0.12.4\deps\uv\include\uv-win.h(251): error C2146: error de sintaxis : falta ';' delante del identificador 'srwlock_' [c:\WSbrainProyect\node_modules\node-rijndael\build\binding.sln]
c:\users\equipo\.node-gyp\0.12.4\deps\uv\include\uv-win.h(251): error C4430: falta el especificador de tipo; se presupone int. Nota: C++ no admite default-int [c:\WSbrainProyect\node_modules\node-rijndael\build\binding.sln] c:\users\equipo\.node-gyp\0.12.4\deps\uv\include\uv-win.h(251): error C4430: falta el especificador de tipo; se presupone int. Nota: C++ no admite default-int [c:\WSbrainProyect\node_modules\node-rijndael\build\binding.sln] ..\src\rijndael.cc(9): fatal error C1083: No se puede abrir el archivo incluir:  'mcrypt.h': No such file or directory [c:\WSbrainProyect\node_modules\node-rijndael\build\binding.sln]

Can you help me?
Thanks

**Comment by skeggse** [comment]
Hello!

I'm not really able to support you - I don't speak spanish well enough to understand the error, and I don't use Windows. It mentions 'mcrypt.h', so you could try installing libmcrypt (which is mentioned in the main README). If that doesn't work, unless you can reproduce this on a Linux system, I can't really help. Sorry.

**Comment by skeggse** [comment]
The latest update may somehow have resolved this - I updated the `nan` version and perhaps that resolved some of the under-the-hood uv stuff.
