### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by schmoove** [skeggse/node-rijndael#15]
Walking through the example steps I get "Error: Symbol rijndael_module not found."

```
> var key = new Buffer('theonetruesecretkeytorulethemall', 'utf-8').toString('base64');
undefined
> var iv = crypto.randomBytes(16).toString('base64');
undefined
> iv
'StEQKssiMONAQnsyq29X4w=='
> var rijndael = require('./examples/rijndael');
```

Do I need to build the node module, or another config step? Thanks!

**Comment by uliporeggia** [comment]
Same problem here!
Seems that this module is out of support.

**Comment by smilingthax** [comment]
In `src/Rijndael.cc`, changing Line 10 from

```
NODE_MODULE(Rijndael, InitAll)
```

to

```
NODE_MODULE(rijndael, InitAll)
```

works for me.
