### ISSUE TITLE
Can't able to decrypt the data encrypted in C#.net.

### ISSUE THREAD

**Issue by Applebit** [skeggse/node-rijndael#16]
//.net code 
//Sorry if you are not from .net background

using System;
using System.Diagnostics;
using System.IO;
using System.Runtime.ExceptionServices;
using System.Security.Cryptography;

namespace Encrypt
{
    static class Program
    {

```
    /// <summary>
    /// Main Entry of the Application
    /// </summary>
    /// <param name="args"></param>
    [HandleProcessCorruptedStateExceptions]
    static void Main(string[] args)
    {
        string original = "Hello, World!";
        try
        {
            byte [] cipher = EncryptString(original);
            Console.WriteLine("Encrypted cipher is :{0}",Convert.ToBase64String(cipher));
            Console.ReadKey();
        }
        catch (CryptographicException exception)
        {
            Trace.Write(exception);
        }
    }

    private static byte[] EncryptString(string message)
    {
        if (message == null || message.Length <= 0)
        throw  new ArgumentNullException(message);
        //Create Cypher algo 
        //note default paddingmode is PKSC7
        RijndaelManaged rijndael = new RijndaelManaged {KeySize = 256};
        rijndael.GenerateIV();
        rijndael.GenerateKey();


        Console.WriteLine("Rindael IV is {0}", Convert.ToBase64String(rijndael.IV));
        Console.WriteLine("Rindeal Key is {0}", Convert.ToBase64String(rijndael.Key));

        ICryptoTransform crypto = rijndael.CreateEncryptor();

        using (MemoryStream memoryStream = new MemoryStream())
        {
            using (CryptoStream cryptoStream = new CryptoStream(memoryStream, crypto, CryptoStreamMode.Write))
            {
                using (StreamWriter sw = new StreamWriter(cryptoStream))
                {
                    sw.Write(message);
                    //sw.Flush();
                }
                return memoryStream.ToArray();
            }

        }
    }
}
```

}

//output
Rindael IV is +VQYSNRSJ4jskZW+ChX13A==
Rindeal Key is 4Mc8auw+ZJrRZAqRkcQfU2YftnGwgqHHt2aCCpn8TBA=
Encrypted cipher is :aKvTCNYg8s9G06uJb9WW8g==

Note - All the data here is base64 string

//nodejs code to decrypt

var iv = '+VQYSNRSJ4jskZW+ChX13A==';
var key = '4Mc8auw+ZJrRZAqRkcQfU2YftnGwgqHHt2aCCpn8TBA=';
var rijndael = require('/home/root-007/node_modules/node-rijndael/examples/rijndael.js');
var encrypteddata = 'aKvTCNYg8s9G06uJb9WW8g==';
var plaintext = rijndael.decrypt(encrypteddata, key, iv);
console.log(plaintext);

//output
P!8£¢H4mÎªt%ª  !&ÀÏ°
              î?          

**Comment by skeggse** [comment]
Your encrypted data uses PKSC7, but the example rijndael script uses null-padding.

**Comment by Applebit** [comment]
I am sorry your code didn't work even with 
paddingmode.None
or
paddingmode.Zeros

**Comment by skeggse** [comment]
What is the default block size for `RijndaelManaged`? Please post your sample data when using `paddingmode.Zeros` and a block size of 256 bits.

**Comment by Applebit** [comment]
The default block size for the RijndaelManaged algorithms is 128 bits. 

Here is the parameterless constructor of Rijndeal class (RijndaelManaged inherits form that class)
protected Rijndael()
{
    this.KeySizeValue = 256;
    this.BlockSizeValue = 128;
    this.FeedbackSizeValue = this.BlockSizeValue;
    this.LegalBlockSizesValue = Rijndael.s_legalBlockSizes;
    this.LegalKeySizesValue = Rijndael.s_legalKeySizes;
}

for more info please follow 
https://msdn.microsoft.com/en-us/library/system.security.cryptography.rijndaelmanaged(v=vs.110).aspx

//sample data
Here all the information is base64 string and assuming paddingmode Zeros with KeySize 256 bit.
Rindael IV is +rNLB50lMq/Hc25cSN9avg==
Rindeal Key is oQNF+m9WVjIEL+ZS1l5h7AZLtzpnjTpxpyA1l3xju9c=
Encrypted cipher is  0BUtWkgiGCXW6hJi9g8nww==

The expected output after decryption is "Hello, World!"(quotes for clarity).

**Comment by skeggse** [comment]
This library only supports rijndael with a block size of 256-bits, and you're using `RijndaelManaged` with a block size of 128-bits, so your use-case is not supported.

AES is a form of rijndael that only supports a 128-bit block size. You should check out the built-in [crypto](https://nodejs.org/api/crypto.html) library.
